behaviors:
  NavigationAgentController:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 2.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      memory:
        sequence_length: 8
        memory_size: 256

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.10
        learning_rate: 0.0003
        network_settings:
          encoding_size: 384
          num_layers: 4

    max_steps: 1000000000
    time_horizon: 512
    summary_freq: 50000
    keep_checkpoints: 10
    checkpoint_interval: 100000
    
environment_parameters:
  maxJumpHeight:
    curriculum:
      - name: Lesson0  
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 0.0
      - name: Lesson1  
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 2.0
      - name: Lesson2  
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 4.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 6.0
      - name: Lesson4
        value: 8.0

  allowMovement:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 1.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 1.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 1.0
      - name: Lesson4
        value: 1.0

  allowJump:
    curriculum:
      - name: Lesson0  
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 0.0
      - name: Lesson1  
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 1.0
      - name: Lesson2  
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 1.0
      - name: Lesson3  
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 1.0
      - name: Lesson4
        value: 1.0

  exploreRoom:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 0.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 0.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 1.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.5
        value: 1.0
      - name: Lesson4
        value: 1.0

  hasObjective:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 0.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 0.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.5
        value: 0.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: NavigationAgentController
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3.0
        value: 1.0
      - name: Lesson4
        value: 1.0